- app/public/css/tt.css
- app/src/controllers/log.js
- app/src/views/calculator.jsx
- app/src/views/page.jsx
Adds a basic calculator with +, -, *, /, backspace, inverse, square root and plus/minus.
As per the SOW I adapted it from an existing calculator.  I chose this one:
http://thecodeplayer.com/walkthrough/javascript-css3-calculator
The adaptation included converting it to React and adding backspace, inverse, square root and plus/minus.
I placed the calculator 50 pixels from the top right corner for now.
> Add basic calculator

- app/public/css/tt.css
- app/src/views/app.js
- app/src/views/calculator.jsx
- app/src/views/chat.jsx
- app/src/views/goalTable.jsx
- app/src/views/notes.js
- app/src/views/page.jsx
- app/src/views/userRegistration.jsx
- gulp/config.js
- gulp/tasks/trim-trailing-spaces.js
- package.json
Trimmed all trailing spaces/tabs in all files under the app folder and created a gulp task named 'trim-trailing-spaces' to automate it.
> Trimmed trailing spaces on all app/* files and added a gulp task

- app/public/css/tt.css
- app/public/index.html
- app/src/views/editor.js
- app/src/views/mathpad.jsx
- app/src/views/page.jsx
- bower.json
- gulp/config.js
Replaced simple calculator with new "MathPad" component.
> Replaced calculator with "MathPad"

- app/src/views/page.jsx
Per request from John Chamberlain the "Circuit X" header should not show in "solo mode"
> Removed "Circuit X" page header for single client configurations

- app/src/views/app.js
Added new top level JSON entry, "logEvent", which is an object whose keys are the event names and whose values have fields for either or both the value and parameters parameter to logEvent().
> Added logEvent logger in activity JSON

- activities/three-resistors-solo-v1.json
- activities/three-resistors-solo-v10.json
- activities/three-resistors-solo-v11.json
- activities/three-resistors-solo-v12.json
- activities/three-resistors-solo-v2.json
- activities/three-resistors-solo-v3.json
- activities/three-resistors-solo-v4.json
- activities/three-resistors-solo-v5.json
- activities/three-resistors-solo-v6.json
- activities/three-resistors-solo-v7.json
- activities/three-resistors-solo-v8.json
- activities/three-resistors-solo-v9.json
- activities/three-resistors-v1.json
- activities/three-resistors-v10.json
- activities/three-resistors-v11.json
- activities/three-resistors-v12.json
- activities/three-resistors-v2.json
- activities/three-resistors-v3.json
- activities/three-resistors-v4.json
- activities/three-resistors-v5.json
- activities/three-resistors-v6.json
- activities/three-resistors-v7.json
- activities/three-resistors-v8.json
- activities/three-resistors-v9.json
Added logEvent to all three-resistor-*v*.json files and image for all three-resistors-solo*.json files
> Updated three-resistors activity JSON files

- app/public/css/tt.css
- app/src/views/page.jsx
- app/src/views/sidebar-chat.jsx
This doesn't support the simple measurement game but that can be added in later if needed.
> Added sidebar chat

- app/public/css/tt.css
- app/src/controllers/user.js
- app/src/data/group-names.js
- app/src/views/userRegistration.jsx
User starts by picking from a pre-defined list of teams, and then,
if there are slots available in that team, a name is automatically
assigned to them.
> Update registration: default teams, names

- activities/three-resistors-level1.json
- activities/three-resistors-level2.json
- activities/three-resistors-level3.json
- activities/three-resistors-level4.json
- activities/three-resistors-level5.json
- activities/three-resistors-solo-level2.json
- activities/three-resistors-solo-level3.json
- activities/three-resistors-solo-level4.json
- activities/three-resistors-solo-level5.json
- app/src/app.js
- app/vendor/pathseg.js
Rebased chrome-fix to master and cherry picked required commits
> Chrome fix for deprecated svg pathSegList

- app/public/css/tt.css
- app/src/views/sidebar-chat.jsx
Make sure students can't type empty messages (extra returns) and force a horizontal wrap if they type a string without spaces in the chat box
> Don't allow empty chat messages and style long messages [#110889730]

- app/src/controllers/user.js
- app/src/views/page.jsx
- app/src/views/sidebar-chat.jsx
Moved the user join/left message suffix from when the message is sent to when it is received.
> Fixed system chat message ordering [#117555951]

- app/src/models/logic-gates/logic-chip.js
- app/src/models/pic/keypad.js
- app/src/models/pic/led.js
- app/src/models/pic/pic.js
- app/src/views/logic-gates/logic-chip.js
- app/src/views/pic/keypad.js
- app/src/views/pic/led.js
- app/src/views/pic/pic.js
- app/src/views/shared/board.js
- app/src/views/shared/pin-label.js
- app/src/views/shared/wire.js
This allows for dropping the probe on pin label instead of just the pin.  The wire component was also updated so that it doesn't consume mouse events while the probe is moving so that you can drop the probe onto a pin with one or more wires already attached to it.
> Added pin label component [#126223245]

- app/src/models/shared/board.js
- app/src/views/logic-gates/app.js
- app/src/views/pic/app.js
- app/src/views/shared/layout.js
- app/src/views/shared/wire.js
Also fixed wire color and hovers.
> Tweaked wire curve generation to exaggerate smaller curves.

- app/src/data/logic-gates/chip-names.js
- app/src/models/logic-gates/logic-chip.js
- app/src/views/logic-gates/logic-chip.js
- app/src/views/shared/logic-chip-drawer.js
Also refactored the chip name map into its own data file since it was being defined in two places.
> Added 7400 (NAND) and 7402 (NOR) logic chips [#128022385] [#128022395]

- app/src/data/logic-gates/chip-names.js
I rearranged the file and neglected to save if before committing the initial file.
> Added missing chip names from chip map.

- activities/logic-gates/single-xor.json
First attempt at changing a JSON script and seeing the result in the browser.
> Updated number of chips

- app/public/logic-gates/index.html
- app/public/pic/index.html
Bower removed the dist folder for jQuery
> Fix path to jQuery bower install in pic and logic gate html files

- activities/breadboard/three-resistors-level1.json
- activities/breadboard/three-resistors-level2.json
- activities/breadboard/three-resistors-level3.json
- activities/breadboard/three-resistors-level4.json
- activities/breadboard/three-resistors-solo-level1.json
- activities/breadboard/three-resistors-solo-level2.json
- activities/breadboard/three-resistors-solo-level3.json
- activities/breadboard/three-resistors-solo-level4.json
Quick change to make the embedded Lara experience a little less confusing when the students reach the goal of the level.  The code already just closes the dialog when the button is pressed, this just changes the text from 'Move To Level X' to 'Ok'.
> Change next button text to 'Ok'

- app/src/controllers/shared/log.js
By adding ?logToConsole to any of the activities a nicely formatted condensed version of the log data is displayed in the developer console to aid in checking the log output.
> Added logToConsole query parameter [#131630059]

- app/public/css/tt.css
- app/src/views/breadboard/enter-unknowns.js
Also fixed z-index of alert dialog so that it covers over the calculator button
> Added logging of entered and correct E and R values in unknowns [#131806595]

- app/src/controllers/pic/board-watcher.js
- app/src/models/pic/led.js
- app/src/views/pic/app.js
- app/src/views/pic/workspace.js
- app/src/views/shared/board.js
- app/src/views/shared/we-got-it.js
Also fixed reversion from commit a080553 - the LED.getPinBitField() method was still using the raw value of the pin instead of the isHigh() helper
> Added PIC solo mode [#130931319]

- app/src/models/shared/connector.js
- app/src/models/shared/hole.js
- app/src/views/logic-gates/constants.js
- app/src/views/pic/constants.js
- app/src/views/shared/colors.js
- app/src/views/shared/connector-selector.js
- app/src/views/shared/connector.js
- app/src/views/shared/events.js
This also changes the top input and output connectors to make the least significant bit be on the right.
> Added way to step through the inputs and way to cycle through all possible inputs [#132784253]

- app/src/models/pic/keypad.js
- app/src/models/pic/pic.js
- app/src/views/shared/pin.js
Also changed pin list setter to skip trised pins instead of setting them to zero and added hover label to pins when they are showing the pin colors
> Fix bug in PIC activity when keypad row is not connected [#133166285]

- activities/breadboard/three-resistors-level1.json
- activities/breadboard/three-resistors-level2.json
Changed “Ok” to “OK” on the button that links to the next activity.
> Corrected typo

- activities/logic-gates/Al's-wonderful-circuit.json
- activities/logic-gates/car-direction-circuit-solo.json
- activities/logic-gates/car-direction-circuit-three.json
- activities/logic-gates/car-direction-circuit-two.json
- activities/logic-gates/car-direction-circuit.json
> Update logic gates

- activities/logic-gates/car-direction-circuit-solo-wiring.json
> Version 1.1

- app/src/controllers/shared/user.js
- app/src/data/shared/group-names.js
- app/src/views/breadboard/userRegistration.jsx
- app/src/views/shared/userRegistration.jsx
If you add ?researchMode to the url the group names change to a single pre-selected choice of "Research Group" with members "Researcher A", "Researcher B", and "Researcher C".
> Added special team for researchers [#135645407]

- activities/logic-gates/inverter-ripple.json
- app/src/models/shared/circuit-resolver.js
- app/src/models/shared/circuit.js
- app/src/views/logic-gates/app.js
- app/src/views/shared/we-got-it.js
- readme.md
* By default it has a 10ms update interval.  You can add "setSpeed" to the query parameters to expose an interface to change the speed (used for tweaking the "look")
* The submit button will show an alert and return if the circuit is not stabilized.  For now "stabilized" means the output doesn't change from one resolution to the next.
* Added an "autoWire" url parameter to automatically do the auto wiring if the JSON allows for it
* Also updated the readme with the "researcherMode" query parameter that I added yesterday
> Added background circuit resolver that is always running to the logic gates environment.

- app/src/models/shared/circuit-resolver.js
- app/src/models/shared/circuit.js
- app/src/models/shared/hole.js
- app/src/models/shared/pin.js
- app/src/models/shared/show-debug-messages.js
- readme.md
This will show the inputs and outputs when hovering over a pin or hole
> Added showDebugMessages url parameter [#136025207]

- app/src/models/logic-gates/logic-chip.js
- app/src/models/pic/pic.js
- app/src/models/shared/board.js
- app/src/models/shared/circuit-resolver.js
- app/src/models/shared/circuit.js
- app/src/models/shared/hole.js
- app/src/models/shared/pin.js
- app/src/views/logic-gates/app.js
- app/src/views/shared/board.js
- app/src/views/shared/connector-hole.js
- readme.md
* The resolver now resolves over each wire in a serial fashion  This will be optimized later today after I complete one other story - I needed to get this in first as there are so many changes.
* The input switches now do not allow for wires to be dragged from them - this enables any click on the switch to toggle the switch
* Fixed a buggy check of the existence of the autoWire url parameter
> Redesigned resolver plus other changes

- app/src/controllers/shared/lara.js
- app/src/controllers/shared/user.js
- app/src/views/breadboard/other-circuits.js
- app/src/views/breadboard/page.jsx
- app/src/views/breadboard/view-other-circuit.js
Also removed wait for global interactive state as that is now passed in initInteractive
> Added class id to Firebase key [#139967403]

- app/src/models/pic/keypad.js
- app/src/models/shared/connector.js
- app/src/models/shared/hole.js
- app/src/views/logic-gates/constants.js
- app/src/views/pic/constants.js
- app/src/views/shared/connector-hole.js
- app/src/views/shared/connector.js
- app/src/views/shared/dip-bank.js
- app/src/views/shared/dip-switch.js
- app/src/views/shared/led-bank.js
DO NOT MERGE YET:  Adding PR so Travis can build a branch on the production server for testing in the demo
> Changed input and outputs to use dip switch and led bank

- activities/logic-gates/adder.json
to 3 inputs and 2 outputs and
added link to index page.
> Changed the single-board adder

- activities/logic-gates/single-board-adder.json
This will also, hopefully, publish the new, improved single-board-adder json file.
> Changed the note

- activities/breadboard/three-resistors-level1.json
- app/src/views/breadboard/app.js
- app/src/views/breadboard/other-circuits.js
- app/src/views/breadboard/sidebar-chat.jsx
- app/src/views/breadboard/view-other-circuit.js
- bower.json
NOTE: for this to work correctly this breadboard PR was merged and bower was updated.
https://github.com/concord-consortium/breadboard/pull/11
> Added option to hide zoom details [#150547608]

- app/public/index.html
- dist/index.html
- package-lock.json
- package.json
Also upgraded require-dir so that it works with node 8
> Fixed missing closing ul tag in homepage that caused formatting to be thrown off.

- app/public/css/tt.css
- app/src/views/breadboard/page.jsx
- app/src/views/breadboard/sidebar-chat.jsx
- app/src/views/breadboard/submitButton.js
1. The message stays the same until all 3 users have joined.
2. Once all users join and then one or more drops off the waiting room shows "Oops! One of your teammates has dropped off."
3. Once the We got it! button is pressed and all the boards are correct when a user leaves the other users see a "Please proceed to the next page." message.
> Added different waiting room messages to show when  users drop off

- app/public/ets-log-converter/index.js
- log-downloader/get-level-map.js
- log-downloader/reprocess-logs.js
Also changed the code so the level is now pulled from the activity json instead of from the level name.
> Added activity name to ETS csv log format [#154215688]

- activities/logic-gates/wonky-example.json
- app/src/models/logic-gates/bbhole.js
- app/src/models/logic-gates/bbstrip.js
- app/src/models/logic-gates/breadboard.js
- app/src/models/logic-gates/logic-chip.js
- app/src/models/shared/board.js
- app/src/models/shared/circuit-resolver.js
- app/src/models/shared/circuit.js
- app/src/models/shared/pin.js
- app/src/views/logic-gates/app.js
- app/src/views/logic-gates/breadboard-hole.js
- app/src/views/logic-gates/breadboard.js
- app/src/views/logic-gates/workspace.js
- app/src/views/shared/board.js
- app/src/views/shared/pin.js
- app/src/views/shared/probe.js
- json-file-formats.md
Changed all of the underlying breadboard model for logic gates to use "ghost wires".
Also updated auto wiring to allow wiring from the top and bottom rails and from the breadboard holes.
> Fixed logic gates breadboard model [#151667598]

- app/src/models/logic-gates/bbhole.js
- app/src/models/logic-gates/breadboard.js
- app/src/models/logic-gates/logic-chip.js
- app/src/models/shared/board.js
- app/src/models/shared/circuit-resolver.js
* The probe now shows "--" when a breadboard strip is not connected
* Also added code to only add the breadboard strip wires when the strip is connected which should speed up the resolver
> Updated connected/unconnect breadboard probe display [#154403670]

- bower.json
This fixes the breadboard touch interface (https://github.com/concord-consortium/breadboard/releases/tag/0.0.13)
> Updated breadboard in bower [#153796240]

- activities/logic-gates/two-board-adder-with-probe.json
- app/src/models/shared/board.js
- app/src/views/logic-gates/app.js
- app/src/views/pic/app.js
- app/src/views/shared/probe.js
Also added two-board-adder-with-probe activity for testing and put a temporary fix in place so the initial mouse down on the probe does not generate an error.
> Fixed bus connectors connected values not being in sync [#154573321]

- app/src/views/logic-gates/breadboard-hole.js
- app/src/views/shared/board.js
- app/src/views/shared/colors.js
- app/src/views/shared/connector-hole.js
- app/src/views/shared/pin.js
Also changed connection drawing code so that it picks the random wire color at the start so that the placed wire is the same color as the drawn wire.
> Removed gray wires [#157626573]

- app/src/controllers/shared/lara.js
Fixes:
1. LARA should not require questions to link to student ID. [#157696526]
2. Can't navigate within LARA once I've selected a team in the interactive. [#157696514]
> Added getInteractiveState request handler [#157696526] [#157696514]

- app/src/views/breadboard/calculator.jsx
Now anytime the calculator component updates and it is open the input field is focused.
> Added focus to calculator [#160741335]
