concord-consortium/teaching-teamwork

app/public/css/editor.css, app/public/index.html, app/src/views/app.js, app/src/views/editor.js, app/src/views/page.jsx, bower.json, gulp/config.js
Moves the editor into the page, visible when "?editor" is appended to the url like this:
http://dougmartin.github.io/concord/teaching-teamwork/integrate-editor/?editor
_NOTE_: If you want to use a server activity like "two-resistors" you should add the hash after the "?editor" like this:
http://dougmartin.github.io/concord/teaching-teamwork/integrate-editor/?editor#two-resistors
The editor is shown at the bottom of the page and works almost the same as the separate page editor.  The differences are:
1. You don't need to save the file to use it - 'Use Local' has been changed to 'Use' - it will restart the activity using the new data
2. The JSON is saved as a string in Firebase so that the ordering of the file is left in place (when it was stored as an object Firebase returned the keys of …
=> Integrated editor into page

app/src/views/app.js
For easier debugging (by not having to enter your name and group) a query string flag of 'no-activity' can be used.  The code just checks for its presense, not its value like this ?no-activity/
=> Added query string flag of 'no-activity' to skip loading the activity

activities/test-oscope.json, gulp/tasks/copy-activities.js, package.json
I decided to add this after changing all those json files - this way we can be sure that at least their syntax is ok.
This uses a combination of two new gulp plugins (gulp-jsonlint and gulp-if) in the copy-activities.js gulp task to narrow the stream to *.json files using gulp-if and to verify the syntax of the json files using gulp-jsonlint.  If there are no errors the output of the gulp run will be the same.  When there are errors the reporter will show the errors in red text.
After running the task I fixed a trailing comma in activities/test-oscope.json
NOTE: once this is merged you will need to run 'npm update' to get the new gulp plugins.
=> Added gulp task to verify activity json files

gulp/config.js, gulp/tasks/copy-activities.js, gulp/tasks/default.js, gulp/tasks/json-lint.js, package.json
Moved the json lint check from copy-activities.js into its own gulp task and added an exit on failure so that the predeploy script will abort.
=> Added json-lint gulp task that exits on failure

app/src/views/mathpad.jsx, app/src/views/page.jsx
Moved the mousemove and mouseup handlers off of the div and onto the window so dragging doesn't get stuck if the mouse moves too fast.
Also hid Mathpad when no activity is selected because opening Mathpad logs an event which causes an error because the logger doesn't have the activityName variable set.
=> Fixed Mathpad dragging bug and hid Mathpad when no activity selected

gulp/tasks/bower-check.js, gulp/tasks/default.js
This is just an insurance policy against deploying the incorrect vendor files.
Like the json-lint check this will exit if the EXIT_ON_ERRORS environment variable is set.
=> Gulp check if the required bower components exist and are the correct version

app/src/views/submitButton.js
This removes the page and adds the following text if all the goals are not correct: "At least one of your team's voltage drops doesn't match that player's goal. Try again.".  If all the goals are met then the table is shown -- I thought that would make for a nice final review of the activity.
=> Don't show all the goals in the submit popup [#97386506]

app/src/controllers/user.js, app/src/views/userRegistration.jsx
This removes the just added functionality of making the username dialog readonly if the cookie is set and instead skips the dialog if the cookie is set.  The group dialog is also skipped if set but the group confirm dialog is still shown so that groups can switch.
=> Skip username and group dialogs if cookie is set [#97655728]

activities/three-resistors-level1.json, activities/three-resistors-level2.json, activities/three-resistors-level3.json, activities/three-resistors-level4.json, activities/three-resistors-level5.json, activities/three-resistors-solo-level1.json, activities/three-resistors-solo-level2.json, activities/three-resistors-solo-level3.json, activities/three-resistors-solo-level4.json, activities/three-resistors-solo-level5.json, app/src/controllers/events.js, app/src/controllers/log.js, app/src/data/workbenchFBConnector.js, app/src/views/app.js, app/src/views/sidebar-chat.jsx
This changes the activity log json files to add a logging config.  The logging config merges the existing logEvents config, exposes a config setting to log component values (previously this was baked into the code) and adds a config setting to log sparks event values with the only value currently being logged being the DMM measurement.  Both the component and event values are included in every log post.
I also updated the client notes activity json files to include units.  This was a different story but it touched the same files.
=> Log dmm values and update activity json notes with units

app/src/data/pic/pic-code.js
The diff is bad because of change from CRLF to LF.  The actual change is on line 453.
=> Fix comment typo in displayed PIC code [#126224121]

app/public/css/tt.css, app/src/views/breadboard/page.jsx
There was an invisible div in the breadboard that overlayed the left side of the sidebar chat textarea causing it not to be able to be selected by the mouse.
=> Moved sidebar chat div in front of breadboard div [#126550023]

activities/logic-gates/adder.json, activities/logic-gates/single-xor.json, app/src/controllers/pic/board-watcher.js, app/src/models/logic-gates/logic-chip.js, app/src/models/shared/board.js, app/src/models/shared/hole.js, app/src/views/logic-gates/app.js, app/src/views/logic-gates/demo-control.js, app/src/views/logic-gates/logic-chip.js, app/src/views/logic-gates/workspace.js, app/src/views/pic/app.js, app/src/views/shared/board.js, app/src/views/shared/connector-hole.js, app/src/views/shared/pin.js, app/src/views/shared/probe.js, app/src/views/shared/ribbon.js
The demo control allows you to add all the components and wires with one button click.  The layout is defined in the activity json.
This also fixes a few bugs [#118940367] [#121079609] [#119397463] and adds a debugging aid:
1. The wires and components are now sent as one object to Firebase.  Before they were two objects which sometimes caused a race condition on the updates since the wires need the components in place first.
2. The 7411 output pin spec was incorrect causing the chip not to resolve correctly.
3. The debug pin colors were rotated 90 degrees for the logic chips since they are also rotated 90 degrees.
4. The component map and list were not being properly cleared when the board was cleared.
5. The logic chip size and width were set to a default size in the model instead of …
=> Add demo control area to logic gate activity

activities/logic-gates/adder.json, activities/logic-gates/single-xor.json, activities/logic-gates/three-board-xor.json, app/public/css/tt.css, app/src/views/logic-gates/app.js, app/src/views/logic-gates/workspace.js, app/src/views/pic/app.js, app/src/views/shared/ribbon.js
This commit also:
- Updates the JSON demo authoring to use named input and output pins
- Moves the online/offline image to the top of the screen for better visibility with >2 boards
- Adds a "three-board-xor" test activity to show that 3 boards looks like
=> Remove two board limitation in logic gate activity [#127831709]

gulp/tasks/browserify.js
This was done as part of the scheduled weekly tech-debt cleanup.
=> Change browserify gulp task to not exit on errors

app/src/models/shared/board.js, app/src/views/shared/board.js, app/src/views/shared/logic-chip-drawer.js
The remote chip delete path was not calling removeComponent() which it now is.   In some cases this caused the chip to be removed from the board but all the wires attached to the chip would remain.  Also moved the logic chip drawer chip counting code directly into the view as a computed value so that when a client reconnects the chip count is not reset to 0.
=> Fixed chip deletes and chip counts [#140139707]

app/public/index.html
I forgot to change the text so the link seemed to be pointing to the xor activity instead of the single board adder activity.
=> Added text to link

app/src/controllers/shared/log.js, app/src/controllers/shared/user.js
This adds Firebase's server time skew to the log time to ensure that out of sync clients all report the same times to the log manager.
=> Server time skew is now added to logging [#145766081]

bower.json
Upgraded to latest version in Bower (16.1.0).  The react-bower repo has frozen at 16.1.0 and will no longer be updated.
https://github.com/reactjs/react-bower
=> Upgrade React to latest version [#157297814]

bower.json
Previously React was upgraded to 16 but this code makes use of extensive React.createClass() calls which are deprecated in 16.
=> Downgrade React to last 15.x version [#157297814]

app/src/models/shared/board.js
The code that handled Firebase updates to the component list did not
update the internal breadboard state causing the logic chip pins to
remain connected to breadboard holes when they were moved.
=> Fix chips not updating when moved [#157062819]

app/public/css/tt.css, app/src/controllers/shared/log.js, app/src/views/shared/version.js, gulp/tasks/browserify.js
Instead of using the package.json version as the displayed version
number in the footer the first 8 characters of the commit hash is shown
as a link to the commit on GitHub.  This was previously a hidden link in
the footer.
The full commit hash is also recoreded under "build" in the log manager
parameters.
=> Change version number to build number [#120136869]

app/src/views/breadboard/submitButton.js
This caused the correct/incorrect state of the unknown values not to be updated if the submit button was pressed before they were entered.
=> Fixed clearing of all unknown value listeners when submit button is closed
